### ISSUE TITLE
Too strict parsing of tsconfig.json

### ISSUE THREAD

**Issue by perbergland** [Adornis/typescript#11]
The parser crashes when encountering sections it doesn't know about - I would prefer if it passed through all options to tsc to avoid needing to update the module whenever MS introduces a new setting.

Example - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html:

```
"compilerOptions": { 
    "incremental": true
},

   packages/adornis:typescript-compiler/typescript-compiler.js:327:13: Format of the tsconfig is invalid: Error: Unknown compiler option 'compilerOptions'.
   at TypeScriptCompiler._parseConfig (packages/adornis:typescript-compiler/typescript-compiler.js:327:13)

```

**Comment by perbergland** [comment]
nevermind I goofed up

**Comment by yorrd** [comment]
:smile: youre working on incremental! Amazing :tada:

**Comment by yorrd** [comment]
do we need to wait for this? just stumbled on it while doing something else

https://github.com/Microsoft/TypeScript/issues/29978

**Comment by perbergland** [comment]
I added
     "incremental": true
 to my tsconfig.json file and it seems to just work (I have tested in watch mode for meteor test and meteor run). No further work needed unless you want to make it a default setting.

**Comment by yorrd** [comment]
how do you make sure it's actually running incrementally? Might that just be the old barbatus cache?

Where is your `.tsbuildinfo`-file?
