### ISSUE TITLE
Typescript 3.6 and incremental compilation

### ISSUE THREAD

**Issue by perbergland** [Adornis/typescript#17]
Seems TS 3.6 finally has support for incremental compilation via the API.

https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#apis-to-support-build-and-incremental
 
I’d be happy to help out if you could provide some pointers on how to set things up locally for testing.

**Comment by yorrd** [comment]
@perbergland sure. Glad you're interested in working on this, we won't get around to it in the comings weeks. Happy to accept any PRs and help testing, we're using this plugin in 10+ projects actively on a daily basis. Basically, you install the plugin and then clone the current version into the packages directory. More specifically:

```
meteor add adornis:typescript

mkdir packages
cd packages
git clone https://github.com/Adornis/typescript
git clone https://github.com/Adornis/typescript-compiler
```

Then you just edit the files in those directories and Meteor automatically recognizes that you're locally editing the plugin and will even hot reload. When done, just push as usual to github. 

Can I help you with pointers in the code somehow?

**Comment by andreastoermer** [comment]
https://github.com/Adornis/typescript-compiler/pull/3
https://github.com/Adornis/typescript/pull/18

I have create pull requests for both components. Please check and maybe you can merge it.

**Comment by yorrd** [comment]
thanks @andreastoermer . Release coming in... dont think that will introduce incremental compiling though even though its good to bump the version after 2 minors

**Comment by perbergland** [comment]
This is now fixed in my new compiler
