### ISSUE TITLE
Path mappings in README

### ISSUE THREAD

**Issue by EECOLOR** [Adornis/typescript#2]
The limitation with 'leading slash imports' has been lifted: https://github.com/Microsoft/TypeScript/issues/13730

Might be nice to adjust this in the readme.

**Comment by yorrd** [comment]
so you don't need those mappings anymore at all and we should just remove the section? That sounds amazing, like TypeScript is actually listening to what people need :wink: 

Sorry, not at my big machine right now.

**Comment by EECOLOR** [comment]
You would still need a mapping, something like this:

```
{
  "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "/*": ["./src/*"]
        }
    }
}
```

You can see more examples in the pull request:
https://github.com/Microsoft/TypeScript/pull/27980/files#diff-8e6145708a8af4240cddde29dac8cd68

**Comment by yorrd** [comment]
It seems like Meteor imports are completely fine without mapping those paths. I'll just remove this for simplicity from the readme because it doesn't seem specific to the package. If you disagree, let me know! 

Thanks for bringing this up!
