### ISSUE TITLE
get rid of barbatus:typescript-runtime

### ISSUE THREAD

**Issue by PopGoesTheWza** [Adornis/typescript#4]
Package.js references `barbatus:typescript-runtime`

https://github.com/Adornis/typescript/blob/9f9daf019fd536984411ff7fd81d50f4f5727187/package.js#L24

This module purpose seem to only wrap around TypeScript `tslib` package. Likely this npm package should be included in the `typescript-compiler` module (unless I am missing something here.)

**Comment by yorrd** [comment]
@PopGoesTheWza so what you're proposing is including `tslib` in the dependencies directly and removing the dependency to `barbatus`? I'm not exactly sure what the package is doing and how it works atm. Do you feel up to writing a pull request with those changes?

**Comment by PopGoesTheWza** [comment]
@yorrd the barbatus:typescript-runtime module only add the tslib package.
This tslib package provides transpiled typescript helpers to improve performance.

This should be better used if the tslib package is directly added in the adornis:typescript-compiler module.

**Comment by perbergland** [comment]
This can be closed now that we instead rely on 
    "importHelpers": true,
in tsconfig
