### ISSUE TITLE
Typescript version selection

### ISSUE THREAD

**Issue by kirstu** [Adornis/typescript#7]
I'm wondering how exactly is the typescript version selection done? 

We're experiencing some weird issues with our build, where it seems that the compilation is happening with an older TS-version than what we have in our node_modules. More specifically the compiler is logging `cant compile because of syntax errors` when it encounters generics in JSX, which have been supported since 2.9 (our version is 3.3.1). 

Any pointers on how to debug the issue would be appreciated, since I have zero knowledge in Meteor packages.

**Comment by kirstu** [comment]
The typescript version seems to be `2.8.3` which probably comes from https://github.com/Adornis/typescript-compiler/blob/ee4c30af35205cb307b6d59b38dbf81ef82ce534/package.js#L18

**Comment by yorrd** [comment]
@kirstu, let me get back to you next week. I was fairly certain that were on 3.3.x, being the latest at the time. Maybe I accidentally reversed the change. Feel free to clone the repo into your `/packages ` directory and try changing the line. Let me know if it helps

**Comment by kirstu** [comment]
Yes, I was able to upgrade the version to `3.3.1` by creating a local package override and bumping the version in `typescript-compiler`'s `package.js`.

**Comment by yorrd** [comment]
@kirstu, feel like pushing that to your repo and starting a pull request? I can accept it today.

**Comment by kirstu** [comment]
@yorrd here you go: https://github.com/Adornis/typescript-compiler/pull/2

**Comment by yorrd** [comment]
accepted and done! Thanks :)
