### ISSUE TITLE
upgrading typescript issues

### ISSUE THREAD

**Issue by MastroLindus** [Adornis/typescript#8]
What is exactly the typescript version used?
I am seeing some errors in my build that look like they come from an old typescript version, even if I have 3.333 in my node_modules folder and I have removed and reinstalled this package (and its dependencies).

If I run tsc from the command line I don't see the same errors output by the meteor build with this plugin...
Is it possible that something is wrongly cached?

Would it be possible to output the typescript version used at the beginning of the compilation step?

**Comment by yorrd** [comment]
I have not yet released a new version. As per https://github.com/Adornis/typescript-compiler/pull/2 , Typescript is now up to date on the development branch. Feel free to clone a local version, I will leave this open until the version is released :)

**Comment by MastroLindus** [comment]
Sorry I am not very familiar with atmosphere packages, after cloning it how do I 
1)build it
2)where precisely do I need to add the output?

**Comment by MastroLindus** [comment]
I tried to do what suggested here  https://stackoverflow.com/questions/18096390/how-to-fork-an-existing-meteorite-package-in-a-clean-way/27992252#27992252

and when I run meteor it seems that the package gets identified and updated, but the build output is the same. As mentioned before, I would be really glad if the build would output the ts version so it would be immediately visible if it's not what you expect

**Comment by MastroLindus** [comment]
So:
1)I can confirm that the issues I am seeing are because of the wrong typescript version. I installed 2.8.3 and compiled manually with it my code and I do see the same errors that I see in the meteor build. Compiling manually with 3.2+ shows no error.
2)I have been trying to make the plugin use a newer version of 2.8 and failed so far. I cloned locally the repo and put it in my project/packages folder, but I still see the same erroneus output. I have been trying to look for plugin or build caches and delete all the ones that I could but I still see the same output
3)I have meanwhile tried to look more into the packages and found out that also that not only the typescript-compiler package hardcodes a typescript version into it, but also package.js in adornis:typescript has a hardcoded version declared (3.2.2). 
To be honest I have the feeling that a version is built and included in the package, otherwise I cannot explain why I still see 2.8.3's output instead of 3.3.
Update: The meteor-typescript's github (https://github.com/barbatus/meteor-typescript) shows that it's a wrapped typescript for meteor, with version 2.8.3 as the latest one updated from barbatus. Could it be possible that the meteor-typescript folder in typescript-compiler is just  a copied version of this, therefore this wrapped 2.8.3 is still the one used by the compiler?

@yorrd  Can you confirm that you had the build run 3.3 (trying some new features as unknown types or "as const" and have it work)? If so, until you publish a new version, could you please tell me how to achieve that locally?

**Comment by KeithGillette** [comment]
@MastroLindus—I, too, got errors when attempting to use TypeScript features beyond 2.8.3. To work around them I:

1. Performed `rm -rf .meteor/local/plugin-cache/barbatus*` (and in my case, the `angular2*` packages which originally installed the `barbaratus*` packages as dependencies)
2. Cloned **both** `adornis/typescript` & `adornis/typescript-compiler` to `packages`
3. Changed the `typescript` version in `package.js` in **both** of those cloned packages to the project version I had installed (in my case 3.2.4)

I am not sure whether all of those steps were strictly required, but the language features I was trying to access are now working after completing that sequence.

**Comment by yorrd** [comment]
@KeithGillette releasing a new package version within a few minutes. As well as updating the typescript version, it will also print out which version it uses now. 

Thanks for the report where you had to remove old barbatus files, that should be removed now (used to share a cache)

**Comment by MastroLindus** [comment]
@yorrd thanks for the great work yorrd, I'll definitely test it out as soon as it's released

**Comment by yorrd** [comment]
@MastroLindus @KeithGillette thanks for reporting, fixed and released :)

@MastroLindus make sure to `meteor reset` once, I'm not 100% certain that the build caches from barbatus and ours don't overlap. No time to investigate further today, if there is stuff left from barbatus, `meteor reset` will remove it. 

Feel free to reopen if this isn't solved
