### ISSUE TITLE
install error on Windows

### ISSUE THREAD

**Issue by Avijobo** [Adornis/typescript#9]
Hi, when installing the latest version (via meteor update), I get this error:

C:\Users\Johan\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Johan\AppData\Local\Temp\mt-v05wjg.9ve7i\os\meteor-typescript\tests\aux.spec.js'
    at Object.fs.openSync (fs.js:646:18)
   ...

meteor reset did not help here... any ideas? Thanks!

**Comment by yorrd** [comment]
which version of the package are you running?

**Comment by Avijobo** [comment]
Currently I am using

adornis:typescript@0.9.6
adornis:typescript-compiler@0.12.6

**Comment by yorrd** [comment]
@Avijobo there is a version 0.9.7, please update :) also, this doesn't seem related to me at first glance. Are you sure this is only happening when you use this package? Try removing it and starting the server without the compiler. Your application won't compile anymore, but when the error disappears, it's not about this package. Just trying to make sure you're looking in the right place

**Comment by Grisu118** [comment]
It works for me with the followoing versions:
>adornis:typescript@0.9.6
>adornis:typescript-compiler@0.12.6

or
>adornis:typescript@0.9.7
>adornis:typescript-compiler@0.12.6

**but not with:**
>adornis:typescript@0.9.7
>adornis:typescript-compiler@0.12.7

Will give it a try with newly released meteor 1.8.1

**Comment by Avijobo** [comment]
Well, I removed the 'adornis:typescript' package, then did a 'meteor update' and all went well during the update. Then I added 'adornis:typescript' again, and got the same error during installation of this package: 

C:\Users\Johan\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^
Error: ENOENT: no such file or directory, open 'C:\Users\Johan\AppData\Local\Temp\mt-1xoqw6p.hci9\os\meteor-typescript\tests\aux.spec.js'

Does the file 'aux.spec.js' says something to you? 

Anyway, cannot add 'adornis:typescript' anymore now, even if I explicitly use 'adornis:typescript@0.9.6' I get the same error... help... I am stuck.

Luckily, to be able to continue my project, I added old 'barbatus:typescript' again, and that works without problems, but is much slower... this is very weird though, until last week, 'adornis:typescript' worked perfectly too.

**Comment by Grisu118** [comment]
Something is wrong with that file also in git

When I try to clone the repo, git reports the follwoing error
> error: unable to create file meteor-typescript/tests/aux.spec.js: No such file or directory

So I think thats also the reason that the file is not present in the package or cannot be created

Git clone works on linux...

The name could be the problem: https://github.com/gajus/react-aux/issues/10
But I have no idea why it works with 0.12.6 and not with 0.12.7

**Comment by yorrd** [comment]
@Avijobo @Grisu118 apparently windows is stupid and has "aux" as and several other file names as reserved names (https://ionicflux.wordpress.com/2006/09/02/windows-reserved-words/). We removed the test folder since it's hopelessly out of date anyways and released a new version. Should be fixed, please let me know if it isn't :)
